server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: zr-zuul
zuul:
  routes:
    zr-provider: /zr-provider/**
    zr-consumer: /zr-consumer/**
  prefix: /api